server:
  port: 9081
  servlet:
    context-path: /microservicio/productos
spring:
  h2:
    console:
      enabled: true
  #BD
  datasource:
    url: jdbc:h2:mem:productBD
    driver-class-name: org.h2.Driver
    platform: h2
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN: -%5p} %n"
